# Generated by Django 3.0.2 on 2020-01-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.DateTimeField()),
                ('tag', models.CharField(max_length=128)),
                ('url', models.TextField()),
                ('domain', models.TextField()),
                ('time_to_load', models.IntegerField()),
                ('load_code', models.IntegerField()),
                ('size', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'web pages',
            },
        ),
    ]
